
health_advice = {
    "Arthritis": [
        "Engage in low-impact exercises, maintain a healthy weight, and use hot/cold therapy for pain relief. Consult a rheumatologist for a customized treatment plan.",
        "Incorporate strength training exercises to support joint health, use assistive devices to reduce strain, and prioritize rest during flare-ups. Consult a rheumatologist for personalized care.",
        "Eat a diet rich in anti-inflammatory foods, stay hydrated, and avoid processed foods. Regular check-ups with a rheumatologist can help manage symptoms.",
        "Practice good posture to reduce joint stress, use ergonomic tools, and engage in flexibility exercises. Professional guidance from a rheumatologist is essential.",
        "Avoid repetitive motions that strain joints, use supportive footwear, and consider aquatic therapy for low-impact exercise. Consult a specialist for tailored treatment.",
        "Manage stress through relaxation techniques, avoid smoking, and limit alcohol consumption. A rheumatologist can provide a comprehensive treatment plan.",
        "Use braces or splints to support affected joints, apply topical pain relievers, and engage in tai chi or yoga for gentle movement. Seek professional advice for symptom management.",
        "Maintain a consistent sleep schedule to improve overall health, use adaptive equipment for daily tasks, and monitor your symptoms. Regular consultations with a rheumatologist are beneficial.",
        "Consider acupuncture for pain relief, take prescribed medications as directed, and avoid overexertion. A rheumatologist can offer specialized treatment options.",
        "Incorporate omega-3 fatty acids into your diet, use heat packs for stiffness, and stay active within your limits. Professional medical advice is crucial for effective management.",
        "Keep a pain diary to track triggers and symptoms, use ice packs to reduce inflammation, and engage in low-impact cardio exercises. Consult a rheumatologist regularly.",
        "Take breaks during repetitive activities, wear compression gloves for hand pain, and participate in a support group. A rheumatologist can help customize your care plan.",
        "Optimize your workstation for comfort, use voice-activated technology to reduce strain, and practice deep breathing exercises. Professional guidance is important for managing arthritis.",
        "Engage in regular stretching routines, avoid high heels, and take vitamin D supplements. A rheumatologist can provide specific recommendations for your condition.",
        "Use a cane or walker if needed, apply paraffin wax treatments for hand pain, and maintain an active social life. Regular medical consultations are essential for effective arthritis management.",
        "Stay informed about new treatments, engage in hobbies that do not strain your joints, and use a heating pad before exercise. A rheumatologist can provide updated care strategies."
    ],
    "Jaundice": [
        "Rest adequately, stay hydrated, and follow dietary and medication advice from your doctor. Regular monitoring is essential.",
        "Avoid alcohol, eat a balanced diet, and ensure proper hygiene. Consult a hepatologist for liver-related issues.",
        "Monitor bilirubin levels regularly, avoid fatty foods, and practice good skin care. Regular check-ups with a healthcare provider are crucial.",
        "Take prescribed medications as directed, avoid smoking, and maintain a healthy lifestyle. Seek advice from a gastroenterologist for ongoing management.",
        "Stay active with light exercises, avoid overexertion, and stay informed about jaundice management. Professional guidance from a general practitioner is beneficial.",
        "Monitor liver function tests regularly, avoid processed foods, and practice good hydration. Regular consultations with a healthcare provider are important.",
        "Use prescribed medications consistently, avoid exposure to toxins, and maintain a healthy weight. Consult a nutritionist for dietary adjustments.",
        "Monitor for signs of worsening symptoms, avoid high-cholesterol foods, and stay active. Regular follow-ups with a general practitioner are crucial.",
        "Stay informed about liver health, avoid high-fat foods, and practice good hygiene. Seek medical advice from a hepatologist for severe cases.",
        "Use natural remedies as recommended, avoid exposure to infections, and practice good skin care. Consult a pharmacist for over-the-counter relief options.",
        "Maintain a balanced diet, avoid excessive alcohol intake, and practice good overall hygiene. Regular consultations with a family doctor are beneficial.",
        "Stay hydrated, avoid overexertion, and use prescribed medications as directed. Seek medical advice from a gastroenterologist for ongoing care.",
        "Take immune-boosting supplements, avoid high-cholesterol foods, and stay informed about jaundice management. Consult a general practitioner for regular monitoring.",
        "Use liver-friendly foods, avoid close contact with infected individuals, and practice good hygiene. Regular check-ups with a healthcare provider are crucial.",
        "Maintain a healthy lifestyle, avoid smoking, and use prescribed medications as directed. Professional guidance from a hepatologist is beneficial."
    ],
    "Bronchial Asthma": [
        "Use inhalers and medications as prescribed, avoid known triggers, and develop an asthma action plan. Regular check-ups with a pulmonologist are crucial.",
        "Maintain good indoor air quality by using air purifiers, avoid exposure to smoke, and keep your living environment clean. Regular medical follow-ups are essential.",
        "Practice breathing exercises to strengthen your lungs, avoid strenuous outdoor activities during high pollen seasons, and use a peak flow meter to monitor your condition. Consult a pulmonologist regularly.",
        "Get vaccinated against influenza and pneumonia, stay hydrated, and avoid cold air exposure. A pulmonologist can provide tailored advice for managing symptoms.",
        "Engage in regular, moderate exercise to improve lung function, avoid allergens, and practice relaxation techniques to reduce stress. Professional guidance is important for asthma management.",
        "Use hypoallergenic bedding, avoid using strong chemical cleaners, and maintain a healthy weight. Regular consultations with a pulmonologist help manage asthma effectively.",
        "Avoid pet dander if you are allergic, use a humidifier during dry seasons, and follow an asthma-friendly diet. Medical advice is essential for long-term asthma control.",
        "Keep a symptom diary to identify triggers, avoid perfumes and scented products, and ensure proper ventilation at home. Regular check-ups with a pulmonologist are beneficial.",
        "Use preventive inhalers regularly even when symptom-free, avoid secondhand smoke, and consider allergy testing. Professional medical advice is crucial for asthma management.",
        "Stay informed about new asthma treatments, use dust-proof covers for pillows and mattresses, and avoid outdoor activities on high pollution days. Regular medical follow-ups are necessary.",
        "Take prescribed long-term control medications, avoid molds and damp areas, and ensure your asthma action plan is up to date. Consult a pulmonologist for personalized care.",
        "Participate in asthma education programs, avoid sudden temperature changes, and use a nebulizer if recommended. Regular consultations with a pulmonologist are vital.",
        "Monitor your breathing patterns, avoid foods that trigger symptoms, and use anti-inflammatory medications as prescribed. Professional advice is essential for managing asthma.",
        "Stay active with low-impact exercises, avoid overexertion, and keep emergency medications accessible. Regular medical check-ups are important for asthma management.",
        "Consider pulmonary rehabilitation programs, use saline nasal sprays to clear airways, and avoid outdoor activities during high humidity. Professional guidance from a pulmonologist is crucial."
    ],
    "Cervical Spondylosis": [
            "Practice good posture, perform neck exercises, and use ergonomic supports. Physical therapy and pain management techniques can be beneficial.",
            "Avoid prolonged sitting, use a supportive pillow, and maintain an active lifestyle. Consult a physical therapist for tailored exercises.",
            "Apply heat or ice to relieve pain, avoid heavy lifting, and perform gentle stretching exercises. Seek advice from an orthopedic specialist.",
            "Engage in low-impact aerobic activities, use a cervical collar if recommended, and consider acupuncture for pain relief. Regular check-ups with a doctor are important.",
            "Take prescribed pain medications as directed, avoid high-impact sports, and ensure proper ergonomic setup at your workstation. Consult a neurologist for nerve-related issues.",
            "Incorporate relaxation techniques like yoga or meditation, avoid activities that strain the neck, and use proper body mechanics. Professional guidance from a rheumatologist can help.",
            "Use topical pain relievers, maintain a healthy weight, and stay hydrated. Regular consultations with a chiropractor may provide relief.",
            "Practice deep breathing exercises to reduce stress, avoid neck hyperextension, and use a supportive mattress. Consult a spine specialist for ongoing pain.",
            "Engage in swimming or water aerobics, use over-the-counter pain relievers, and perform range-of-motion exercises. Regular check-ups with a pain management specialist are beneficial.",
            "Avoid carrying heavy bags on one shoulder, perform isometric neck exercises, and consider physical therapy. Professional advice from an orthopedic surgeon may be necessary.",
            "Use a standing desk if possible, practice mindfulness to manage pain, and avoid sudden neck movements. Consult a rheumatologist for chronic conditions.",
            "Take frequent breaks from screen time, avoid cradling the phone between your ear and shoulder, and use traction if recommended. Regular follow-ups with a physical therapist are important.",
            "Maintain an anti-inflammatory diet, avoid smoking, and use relaxation techniques. Professional guidance from a neurologist can aid in managing symptoms.",
            "Use ergonomic tools and devices, practice gentle neck massages, and avoid activities that worsen pain. Consult an occupational therapist for workplace modifications.",
            "Stay active with low-impact exercises, avoid repetitive neck movements, and use supportive footwear. Regular check-ups with a pain specialist are crucial."
    ],
    "Chickenpox": [
        "Get plenty of rest, maintain good hygiene, and avoid scratching the blisters. Consult a doctor for antiviral treatments if needed.",
        "Use calamine lotion to soothe itching, keep fingernails short, and wear loose, comfortable clothing. Consult a pediatrician for children with severe symptoms.",
        "Stay hydrated, take lukewarm baths with baking soda or oatmeal, and avoid contact with pregnant women. Seek advice from an infectious disease specialist if complications arise.",
        "Use over-the-counter pain relievers, avoid spicy and acidic foods, and keep the skin cool. Regular check-ups with a healthcare provider are essential.",
        "Practice good hand hygiene, avoid sharing personal items, and use antiviral medications as prescribed. Consult a dermatologist for severe skin reactions.",
        "Apply cool compresses to itchy areas, avoid hot showers, and ensure adequate fluid intake. Professional guidance from a general practitioner is important.",
        "Take antihistamines for itching, avoid tight-fitting clothes, and use hypoallergenic soap. Regular consultations with a family doctor are beneficial.",
        "Monitor for signs of secondary infection, avoid strenuous activities, and maintain a healthy diet. Seek medical attention from a pediatric infectious disease specialist if needed.",
        "Rest in a cool, dark room, avoid scratching with gloves if necessary, and keep the environment clean. Consult a nurse practitioner for symptom management.",
        "Use soothing lotions, avoid exposure to extreme temperatures, and practice good oral hygiene. Regular follow-ups with a healthcare provider are crucial.",
        "Stay isolated to prevent spreading the virus, use medicated creams as recommended, and avoid strenuous activities. Consult a pharmacist for over-the-counter remedies.",
        "Take immune-boosting supplements, avoid smoking and alcohol, and practice relaxation techniques. Professional advice from a general practitioner can help manage symptoms.",
        "Use cooling gels for relief, avoid spicy foods, and ensure proper rest. Regular check-ups with a pediatrician are important for children.",
        "Maintain a balanced diet, avoid scratching by using mittens, and use antiviral treatments as prescribed. Seek medical advice from an infectious disease specialist if complications occur.",
        "Stay away from public places until fully recovered, use mild soap for bathing, and ensure proper hydration. Regular consultations with a family doctor are beneficial."
    ],
    "Common Cold": [
        "Rest well, stay hydrated, and use over-the-counter remedies for symptom relief. Seek medical help if symptoms persist or worsen.",
        "Use saline nasal drops, avoid dairy products if they worsen congestion, and keep your head elevated while sleeping. Consult a general practitioner for severe symptoms.",
        "Take vitamin C and zinc supplements, avoid smoking, and practice good hand hygiene. Regular check-ups with a healthcare provider are important.",
        "Use a humidifier to keep the air moist, avoid crowded places, and drink warm fluids. Seek advice from an otolaryngologist for persistent congestion.",
        "Gargle with salt water, avoid alcohol, and use throat lozenges for relief. Consult a pharmacist for over-the-counter medication recommendations.",
        "Stay warm, avoid sudden temperature changes, and use eucalyptus oil for steam inhalation. Professional guidance from a general practitioner is beneficial.",
        "Take decongestants as needed, avoid overexertion, and maintain a healthy diet. Regular consultations with a family doctor can help manage symptoms.",
        "Use honey and lemon in warm water, avoid caffeine, and practice good respiratory hygiene. Consult a nurse practitioner for ongoing symptoms.",
        "Get plenty of sleep, avoid secondhand smoke, and use a nasal spray if needed. Regular follow-ups with a healthcare provider are crucial.",
        "Practice breathing exercises, avoid dairy if it increases mucus production, and use menthol rubs for relief. Seek medical advice from an allergist if symptoms are allergy-related.",
        "Stay indoors during extreme weather, avoid stress, and use herbal teas for soothing relief. Consult a naturopath for natural remedies.",
        "Keep hydrated with warm soups and broths, avoid sugar-rich foods, and use over-the-counter cough syrups as needed. Regular check-ups with a general practitioner are important.",
        "Use garlic in your diet for its antiviral properties, avoid close contact with sick individuals, and keep your living area clean. Professional advice from a general practitioner can help.",
        "Practice nasal irrigation with saline solution, avoid touching your face, and use a heating pad for sinus relief. Regular consultations with a family doctor are beneficial.",
        "Stay active with light exercises, avoid dehydration, and use vitamin supplements to boost immunity. Consult a healthcare provider for persistent symptoms."
    ],
    "Dengue": [
        "Ensure adequate hydration, rest, and manage fever with acetaminophen. Immediate medical attention is vital as dengue can progress rapidly.",
        "Avoid mosquito bites by using repellents, wear long-sleeved clothing, and use mosquito nets. Consult an infectious disease specialist for severe cases.",
        "Monitor for warning signs like severe abdominal pain, vomiting, and bleeding, and avoid aspirin and ibuprofen. Regular check-ups with a healthcare provider are crucial.",
        "Take prescribed medications as directed, avoid standing water around the home, and maintain a clean environment. Seek advice from a general practitioner for ongoing symptoms.",
        "Use cooling measures to reduce fever, avoid strenuous activities, and ensure proper nutrition. Professional guidance from an infectious disease specialist is important.",
        "Stay in well-screened or air-conditioned areas, avoid outdoor activities during peak mosquito hours, and practice good hygiene. Regular consultations with a healthcare provider are beneficial.",
        "Monitor fluid intake, avoid sudden movements that may cause fainting, and use paracetamol for pain relief. Consult a pediatrician for children with dengue.",
        "Maintain a symptom diary, avoid alcohol, and take rest breaks throughout the day. Regular follow-ups with a family doctor are essential.",
        "Use natural mosquito repellents like citronella, avoid heavily scented soaps and perfumes, and practice mindfulness to manage stress. Seek medical advice from an infectious disease specialist if needed.",
        "Stay away from crowded places during outbreaks, avoid dehydration, and practice yoga or meditation for relaxation. Consult a nurse practitioner for symptom management.",
        "Monitor platelet count regularly, avoid contact sports, and use light blankets to stay warm. Professional advice from a general practitioner can help manage symptoms.",
        "Stay informed about dengue prevention strategies, avoid exposure to infected individuals, and use insecticide-treated bed nets. Regular check-ups with a healthcare provider are crucial.",
        "Take immune-boosting supplements, avoid spicy foods, and use natural remedies like papaya leaf extract. Consult a pharmacist for over-the-counter relief options.",
        "Stay cool with fans or air conditioning, avoid prolonged sun exposure, and ensure adequate rest. Regular consultations with a family doctor are beneficial.",
        "Keep your living area free from mosquito breeding sites, avoid tight clothing, and use soothing lotions for skin relief. Seek medical advice from an infectious disease specialist for severe cases."
    ],
    "Acne": [
            "Adopt a consistent skincare routine using gentle products, avoid touching or picking at the skin, and consider non-prescription topical treatments. Severe cases should be evaluated by a dermatologist.",
            "Maintain a balanced diet rich in fruits and vegetables, drink plenty of water, and avoid excessive sugar and dairy intake. Persistent issues should be discussed with a healthcare professional.",
            "Keep your hair clean and away from your face, avoid using heavy makeup, and choose non-comedogenic products. Consult a dermatologist for persistent cases.",
            "Exercise regularly to improve circulation and reduce stress, shower immediately after sweating, and use a gentle cleanser. Seek medical advice for stubborn acne.",
            "Change pillowcases and towels frequently, avoid excessive sun exposure, and use oil-free sunscreen. Persistent acne may require professional treatment.",
            "Reduce stress through mindfulness practices like yoga or meditation, and avoid high-glycemic foods. Severe or cystic acne should be treated by a dermatologist.",
            "Use a mild exfoliant to remove dead skin cells, avoid harsh scrubbing, and moisturize with non-comedogenic products. Consider professional advice for long-term acne.",
            "Avoid smoking and secondhand smoke, keep your phone screen clean, and avoid touching your face. Professional consultation is recommended for chronic acne.",
            "Incorporate a retinoid cream into your skincare routine, avoid popping pimples, and use a clay mask weekly. See a dermatologist for persistent issues.",
            "Ensure adequate sleep and rest, manage hormonal changes with appropriate medication, and consider light therapy. Severe acne should be professionally evaluated.",
            "Use a toner to balance your skin’s pH, avoid greasy and fried foods, and use a topical antibiotic if necessary. Professional treatment is recommended for ongoing acne problems.",
            "Wash your face twice daily with a gentle cleanser, avoid using too many skincare products at once, and consider a salicylic acid treatment. Persistent acne needs dermatologist attention.",
            "Choose skincare products free of alcohol and fragrance, avoid stress triggers, and maintain a regular skincare routine. Consult a professional for unresponsive acne.",
            "Stay hydrated throughout the day, avoid tight clothing that causes friction, and consider zinc supplements. Persistent acne should be seen by a dermatologist.",
            "Use a separate towel for your face, avoid using hot water on your skin, and try tea tree oil for its antibacterial properties. Professional advice is essential for severe acne.",
            "Maintain good hygiene by cleaning makeup brushes regularly, avoid excessive caffeine, and use an aloe vera gel. Seek medical advice for chronic acne issues."
    ],
    "Hemorrhoids": [
        "Adopt a high-fiber diet, maintain good hygiene, and consider stool softeners. Persistent symptoms should be evaluated by a doctor.",
        "Use over-the-counter creams and ointments, avoid prolonged sitting, and stay hydrated. Consult a gastroenterologist for severe cases.",
        "Practice regular physical activity, avoid heavy lifting, and take warm sitz baths. Regular check-ups with a healthcare provider are important.",
        "Use cold compresses to reduce swelling, avoid straining during bowel movements, and eat a balanced diet. Seek advice from a proctologist for ongoing symptoms.",
        "Take oral pain relievers as needed, avoid processed foods, and practice good toilet habits. Professional guidance from a general practitioner is beneficial.",
        "Maintain a healthy weight, avoid spicy foods, and use moist towelettes instead of dry toilet paper. Regular consultations with a family doctor can help manage symptoms.",
        "Use a donut-shaped cushion for sitting, avoid alcohol and caffeine, and perform pelvic floor exercises. Consult a colorectal surgeon for severe hemorrhoids.",
        "Monitor your symptoms, avoid long periods of standing, and use natural remedies like witch hazel. Regular follow-ups with a healthcare provider are crucial.",
        "Stay hydrated, avoid over-the-counter laxatives, and practice mindfulness to reduce stress. Seek medical advice from a dietitian for dietary adjustments.",
        "Use fiber supplements if necessary, avoid smoking, and keep the anal area clean and dry. Consult a pharmacist for over-the-counter relief options.",
        "Take frequent breaks if sitting for long periods, avoid scratching the affected area, and use herbal remedies for relief. Professional advice from a general practitioner can help.",
        "Maintain a regular bowel routine, avoid tight clothing, and practice good posture. Regular consultations with a family doctor are beneficial.",
        "Stay active with low-impact exercises, avoid overexertion, and use ice packs for pain relief. Seek medical advice from a gastroenterologist if symptoms persist.",
        "Use topical anesthetics for severe pain, avoid heavy meals, and maintain good overall health. Consult a proctologist for specialized treatment.",
        "Take care during pregnancy to avoid straining, avoid lifting heavy objects, and practice gentle yoga for relief. Regular check-ups with a healthcare provider are crucial."
    ],
    "Fungal Infection": [
        "Keep the area clean and dry, use antifungal treatments, and avoid sharing personal items. See a dermatologist if the infection persists.",
        "Wear breathable fabrics, avoid walking barefoot in public areas, and maintain good hygiene. Consult a general practitioner for ongoing symptoms.",
        "Use antifungal powders, avoid tight-fitting clothing, and ensure proper ventilation. Regular check-ups with a healthcare provider are important.",
        "Apply natural remedies like tea tree oil, avoid scratching the affected area, and use separate towels for the infected region. Seek advice from a dermatologist for persistent cases.",
        "Maintain a healthy diet, avoid sugary foods, and practice good skin care. Professional guidance from a general practitioner is beneficial.",
        "Use over-the-counter antifungal creams, avoid excessive sweating, and keep your nails short and clean. Regular consultations with a family doctor can help manage symptoms.",
        "Take oral antifungal medications as prescribed, avoid contact with infected animals, and practice good foot hygiene. Consult a podiatrist for fungal infections of the feet.",
        "Monitor for signs of secondary infection, avoid sharing shoes or socks, and use antifungal shampoos if necessary. Regular follow-ups with a healthcare provider are crucial.",
        "Stay hydrated, avoid hot and humid environments, and practice relaxation techniques to reduce stress. Seek medical advice from a dermatologist for recurring infections.",
        "Use medicated soaps, avoid exposure to infected individuals, and practice good nail care. Consult a pharmacist for over-the-counter relief options.",
        "Maintain a clean living environment, avoid prolonged exposure to water, and use antifungal sprays for shoes. Professional advice from a general practitioner can help.",
        "Practice good oral hygiene, avoid close contact with others, and use antifungal mouthwashes if needed. Regular consultations with a family doctor are beneficial.",
        "Stay active with light exercises, avoid using strong detergents, and keep the skin dry. Seek medical advice from a dermatologist for severe cases.",
        "Use antifungal nail polish if necessary, avoid walking barefoot in damp areas, and maintain good overall health. Consult a podiatrist for specialized treatment.",
        "Take care to avoid reinfection, avoid wearing synthetic fabrics, and use antifungal treatments as directed. Regular check-ups with a healthcare provider are crucial."
    ],
    "Hypertension": [
        "Maintain a balanced diet, engage in regular exercise, reduce salt intake, and adhere to prescribed medications. Regular health check-ups are essential.",
        "Monitor blood pressure regularly, avoid stress, and maintain a healthy weight. Consult a cardiologist for personalized treatment plans.",
        "Reduce caffeine intake, practice relaxation techniques, and avoid smoking. Regular consultations with a general practitioner can help manage hypertension.",
        "Take prescribed medications consistently, avoid excessive alcohol consumption, and incorporate potassium-rich foods into your diet. Seek advice from a nutritionist for dietary adjustments.",
        "Stay active with aerobic exercises, avoid processed foods, and practice mindfulness meditation. Professional guidance from a general practitioner is beneficial.",
        "Monitor cholesterol levels, avoid high-fat foods, and maintain a regular exercise routine. Regular follow-ups with a healthcare provider are crucial.",
        "Use a home blood pressure monitor, avoid high-sodium foods, and stay hydrated. Consult a pharmacist for medication management.",
        "Practice deep breathing exercises, avoid high-stress situations, and stay informed about hypertension management. Regular check-ups with a cardiologist are important.",
        "Maintain a diet rich in fruits and vegetables, avoid sugary beverages, and engage in regular physical activity. Seek medical advice from a general practitioner for ongoing management.",
        "Take part in hypertension education programs, avoid fast food, and use relaxation techniques like yoga. Consult a nurse practitioner for routine monitoring.",
        "Maintain good sleep hygiene, avoid high-cholesterol foods, and practice regular physical activity. Regular consultations with a family doctor can help manage symptoms.",
        "Stay informed about hypertension medications, avoid sedentary behavior, and practice good sleep habits. Seek advice from a general practitioner for ongoing care.",
        "Use relaxation techniques to manage stress, avoid over-the-counter medications that raise blood pressure, and stay active. Consult a cardiologist for specialized care.",
        "Maintain a low-sodium diet, avoid excessive alcohol intake, and monitor blood pressure regularly. Regular check-ups with a healthcare provider are essential.",
        "Engage in regular physical activity, avoid trans fats, and take prescribed medications as directed. Professional guidance from a general practitioner is beneficial."
    ],
    "Psoriasis": [
            "Keep the skin moisturized, use prescribed treatments, and avoid known triggers. Regular dermatologist consultations are recommended.",
            "Avoid harsh soaps, practice good skin care, and use medicated shampoos if needed. Consult a dermatologist for ongoing management.",
            "Stay hydrated, avoid smoking, and practice good skin hygiene. Regular check-ups with a healthcare provider are crucial.",
            "Use prescribed medications consistently, avoid overexertion, and practice good hand hygiene. Seek advice from a dermatologist for ongoing management.",
            "Stay active with light exercises, avoid overexertion, and maintain a healthy diet. Professional guidance from a general practitioner is beneficial.",
            "Monitor for signs of worsening symptoms, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
            "Use prescribed medications consistently, avoid exposure to cold air, and practice good hand hygiene. Consult a nutritionist for dietary adjustments.",
            "Monitor for signs of secondary infection, avoid close contact with infected individuals, and use prescribed medications consistently. Regular follow-ups with a healthcare provider are crucial.",
            "Stay hydrated, avoid exposure to cold air, and practice good hand hygiene. Seek medical advice from a dermatologist for ongoing management.",
            "Use prescribed medications consistently, avoid smoking, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
            "Monitor for signs of worsening symptoms, avoid exposure to cold air, and stay hydrated. Regular check-ups with a healthcare provider are crucial.",
            "Take prescribed medications consistently, avoid exposure to pollutants, and stay informed about psoriasis management. Seek advice from a general practitioner for ongoing care.",
            "Use prescribed medications consistently, avoid exposure to cold air, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
            "Monitor for signs of secondary infection, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
            "Stay active with light exercises, avoid overexertion, and practice good skin hygiene. Seek medical advice from a dermatologist for ongoing management."
    ],
    "Malaria": [
        "Take prescribed antimalarial drugs, rest, and manage fever. Seek prompt medical care for severe cases.",
        "Avoid mosquito bites by using repellents, wear long-sleeved clothing, and use mosquito nets. Consult an infectious disease specialist for severe cases.",
        "Monitor for warning signs like severe abdominal pain, vomiting, and bleeding, and avoid aspirin and ibuprofen. Regular check-ups with a healthcare provider are crucial.",
        "Take prescribed medications as directed, avoid standing water around the home, and maintain a clean environment. Seek advice from a general practitioner for ongoing symptoms.",
        "Use cooling measures to reduce fever, avoid strenuous activities, and ensure proper nutrition. Professional guidance from an infectious disease specialist is important.",
        "Stay in well-screened or air-conditioned areas, avoid outdoor activities during peak mosquito hours, and practice good hygiene. Regular consultations with a healthcare provider are beneficial.",
        "Monitor fluid intake, avoid sudden movements that may cause fainting, and use paracetamol for pain relief. Consult a pediatrician for children with malaria.",
        "Maintain a symptom diary, avoid alcohol, and take rest breaks throughout the day. Regular follow-ups with a family doctor are essential.",
        "Use natural mosquito repellents like citronella, avoid heavily scented soaps and perfumes, and practice mindfulness to manage stress. Seek medical advice from an infectious disease specialist if needed.",
        "Stay away from crowded places during outbreaks, avoid dehydration, and practice yoga or meditation for relaxation. Consult a nurse practitioner for symptom management.",
        "Monitor platelet count regularly, avoid contact sports, and use light blankets to stay warm. Professional advice from a general practitioner can help manage symptoms.",
        "Stay informed about malaria prevention strategies, avoid exposure to infected individuals, and use insecticide-treated bed nets. Regular check-ups with a healthcare provider are crucial.",
        "Take immune-boosting supplements, avoid spicy foods, and use natural remedies like papaya leaf extract. Consult a pharmacist for over-the-counter relief options.",
        "Stay cool with fans or air conditioning, avoid prolonged sun exposure, and ensure adequate rest. Regular consultations with a family doctor are beneficial.",
        "Keep your living area free from mosquito breeding sites, avoid tight clothing, and use soothing lotions for skin relief. Seek medical advice from an infectious disease specialist for severe cases."
    ],
    "Migraine": [
        "Identify and avoid triggers, manage stress, and use pain relief medications as needed. Consult a neurologist for specialized management.",
        "Maintain a regular sleep schedule, avoid caffeine, and practice relaxation techniques. Regular check-ups with a healthcare provider are important.",
        "Keep a headache diary to track triggers, avoid loud noises, and stay hydrated. Seek advice from a neurologist for ongoing management.",
        "Use prescribed medications consistently, avoid strong odors, and practice good posture. Professional guidance from a general practitioner is beneficial.",
        "Monitor for early signs of an attack, avoid skipping meals, and practice mindfulness meditation. Regular consultations with a healthcare provider are crucial.",
        "Use cold or warm compresses, avoid exposure to bright lights, and maintain a healthy diet. Consult a pharmacist for over-the-counter relief options.",
        "Take preventive medications if prescribed, avoid alcohol, and practice good sleep hygiene. Regular follow-ups with a neurologist are important.",
        "Use relaxation techniques like yoga or tai chi, avoid high-stress situations, and stay active. Seek medical advice from a general practitioner for ongoing care.",
        "Stay informed about new migraine treatments, avoid processed foods, and practice good hydration. Consult a dietitian for dietary adjustments.",
        "Use natural remedies like peppermint oil, avoid overexertion, and practice regular physical activity. Professional advice from a neurologist can help manage symptoms.",
        "Monitor for signs of aura, avoid exposure to allergens, and use prescription medications as directed. Regular consultations with a healthcare provider are beneficial.",
        "Take immune-boosting supplements, avoid high-sodium foods, and stay informed about migraine triggers. Seek advice from a general practitioner for regular monitoring.",
        "Use acupressure techniques for relief, avoid extreme weather changes, and practice good overall health. Consult a neurologist for specialized care.",
        "Maintain a balanced diet, avoid smoking, and use prescribed medications as directed. Regular check-ups with a healthcare provider are crucial.",
        "Stay active with low-impact exercises, avoid dehydration, and practice relaxation techniques. Professional guidance from a neurologist is beneficial."
    ],
    "Pneumonia": [
        "Follow antibiotic prescriptions, rest, stay hydrated, and monitor symptoms closely. Seek immediate medical attention for severe symptoms.",
        "Avoid smoking, practice good hand hygiene, and use a humidifier to ease breathing. Consult a pulmonologist for severe cases.",
        "Take prescribed medications consistently, avoid exposure to pollutants, and stay informed about pneumonia management. Regular check-ups with a healthcare provider are crucial.",
        "Use over-the-counter medications for symptom relief, avoid strenuous activities, and practice good respiratory hygiene. Seek advice from a general practitioner for ongoing management.",
        "Stay active with light exercises, avoid overexertion, and maintain a healthy diet. Professional guidance from a general practitioner is beneficial.",
        "Monitor for signs of worsening symptoms, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Use prescribed medications consistently, avoid exposure to cold air, and practice good hand hygiene. Consult a nutritionist for dietary adjustments.",
        "Monitor for signs of secondary infection, avoid close contact with infected individuals, and use prescribed medications consistently. Regular follow-ups with a healthcare provider are crucial.",
        "Stay hydrated, avoid exposure to cold air, and practice good hand hygiene. Seek medical advice from a pulmonologist for ongoing management.",
        "Use prescribed medications consistently, avoid smoking, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of worsening symptoms, avoid exposure to cold air, and stay hydrated. Regular check-ups with a healthcare provider are crucial.",
        "Take prescribed medications consistently, avoid exposure to pollutants, and stay informed about pneumonia management. Seek advice from a general practitioner for ongoing care.",
        "Use prescribed medications consistently, avoid exposure to cold air, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of secondary infection, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Stay active with light exercises, avoid overexertion, and practice good respiratory hygiene. Seek medical advice from a pulmonologist for ongoing management."
    ],
    "Typhoid": [
        "Adhere to antibiotic regimens, rest, and stay hydrated. Follow dietary precautions and consult a doctor for proper management.",
        "Avoid raw and unwashed foods, practice good hand hygiene, and drink only purified water. Consult an infectious disease specialist for severe cases.",
        "Monitor for signs of complications, avoid close contact with others, and take prescribed medications consistently. Regular check-ups with a healthcare provider are crucial.",
        "Use over-the-counter medications for symptom relief, avoid strenuous activities, and practice good food hygiene. Seek advice from a general practitioner for ongoing management.",
        "Stay active with light exercises, avoid overexertion, and maintain a healthy diet. Professional guidance from a general practitioner is beneficial.",
        "Monitor for signs of worsening symptoms, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Use prescribed medications consistently, avoid exposure to cold air, and practice good hand hygiene. Consult a nutritionist for dietary adjustments.",
        "Monitor for signs of secondary infection, avoid close contact with infected individuals, and use prescribed medications consistently. Regular follow-ups with a healthcare provider are crucial.",
        "Stay hydrated, avoid exposure to cold air, and practice good hand hygiene. Seek medical advice from an infectious disease specialist for ongoing management.",
        "Use prescribed medications consistently, avoid smoking, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of worsening symptoms, avoid exposure to cold air, and stay hydrated. Regular check-ups with a healthcare provider are crucial.",
        "Take prescribed medications consistently, avoid exposure to pollutants, and stay informed about typhoid management. Seek advice from a general practitioner for ongoing care.",
        "Use prescribed medications consistently, avoid exposure to cold air, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of secondary infection, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Stay active with light exercises, avoid overexertion, and practice good food hygiene. Seek medical advice from an infectious disease specialist for ongoing management."
    ],
    "Varicose Veins": [
        "Elevate your legs, exercise regularly, and wear compression stockings. Consult a vascular specialist for further evaluation and treatment.",
        "Avoid prolonged standing, practice good leg hygiene, and maintain a healthy weight. Regular consultations with a healthcare provider are important.",
        "Use prescribed medications consistently, avoid overexertion, and practice good hand hygiene. Seek advice from a vascular specialist for ongoing management.",
        "Stay active with light exercises, avoid overexertion, and maintain a healthy diet. Professional guidance from a general practitioner is beneficial.",
        "Monitor for signs of worsening symptoms, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are crucial.",
        "Use prescribed medications consistently, avoid exposure to cold air, and practice good hand hygiene. Consult a nutritionist for dietary adjustments.",
        "Monitor for signs of secondary infection, avoid close contact with infected individuals, and use prescribed medications consistently. Regular follow-ups with a healthcare provider are important.",
        "Stay hydrated, avoid exposure to cold air, and practice good hand hygiene. Seek medical advice from a vascular specialist for ongoing management.",
        "Use prescribed medications consistently, avoid smoking, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of worsening symptoms, avoid exposure to cold air, and stay hydrated. Regular check-ups with a healthcare provider are crucial.",
        "Take prescribed medications consistently, avoid exposure to pollutants, and stay informed about varicose veins management. Seek advice from a general practitioner for ongoing care.",
        "Use prescribed medications consistently, avoid exposure to cold air, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of secondary infection, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Stay active with light exercises, avoid overexertion, and practice good leg hygiene. Seek medical advice from a vascular specialist for ongoing management."
    ],
    "Allergy": [
        "Identify and avoid allergens, use antihistamines as needed, and consult an allergist for comprehensive care.",
        "Maintain good indoor air quality, practice good hand hygiene, and stay hydrated. Consult a healthcare provider for severe symptoms.",
        "Use prescribed medications consistently, avoid overexertion, and practice good hand hygiene. Seek advice from an allergist for ongoing management.",
        "Stay active with light exercises, avoid overexertion, and maintain a healthy diet. Professional guidance from a general practitioner is beneficial.",
        "Monitor for signs of worsening symptoms, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Use prescribed medications consistently, avoid exposure to cold air, and practice good hand hygiene. Consult a nutritionist for dietary adjustments.",
        "Monitor for signs of secondary infection, avoid close contact with infected individuals, and use prescribed medications consistently. Regular follow-ups with a healthcare provider are crucial.",
        "Stay hydrated, avoid exposure to cold air, and practice good hand hygiene. Seek medical advice from an allergist for ongoing management.",
        "Use prescribed medications consistently, avoid smoking, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of worsening symptoms, avoid exposure to cold air, and stay hydrated. Regular check-ups with a healthcare provider are crucial.",
        "Take prescribed medications consistently, avoid exposure to pollutants, and stay informed about allergy management. Seek advice from a general practitioner for ongoing care.",
        "Use prescribed medications consistently, avoid exposure to cold air, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of secondary infection, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Stay active with light exercises, avoid overexertion, and practice good hand hygiene. Seek medical advice from an allergist for ongoing management."
    ],
    "Diabetes": [
        "Maintain a balanced diet, exercise regularly, monitor blood sugar levels, and take prescribed medications. Regular visits to an endocrinologist are crucial.",
        "Avoid sugary foods, practice good hand hygiene, and stay hydrated. Consult a healthcare provider for severe symptoms.",
        "Use prescribed medications consistently, avoid overexertion, and practice good hand hygiene. Seek advice from an endocrinologist for ongoing management.",
        "Stay active with light exercises, avoid overexertion, and maintain a healthy diet. Professional guidance from a general practitioner is beneficial.",
        "Monitor for signs of worsening symptoms, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Use prescribed medications consistently, avoid exposure to cold air, and practice good hand hygiene. Consult a nutritionist for dietary adjustments.",
        "Monitor for signs of secondary infection, avoid close contact with infected individuals, and use prescribed medications consistently. Regular follow-ups with a healthcare provider are crucial.",
        "Stay hydrated, avoid exposure to cold air, and practice good hand hygiene. Seek medical advice from an endocrinologist for ongoing management.",
        "Use prescribed medications consistently, avoid smoking, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of worsening symptoms, avoid exposure to cold air, and stay hydrated. Regular check-ups with a healthcare provider are crucial.",
        "Take prescribed medications consistently, avoid exposure to pollutants, and stay informed about diabetes management. Seek advice from a general practitioner for ongoing care.",
        "Use prescribed medications consistently, avoid exposure to cold air, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of secondary infection, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Stay active with light exercises, avoid overexertion, and practice good hand hygiene. Seek medical advice from an endocrinologist for ongoing management."
    ],
    "Drug Reaction": [
        "Stop the suspected medication, seek immediate medical attention if severe, and inform healthcare providers about the reaction.",
        "Maintain good hand hygiene, practice good hand hygiene, and stay hydrated. Consult a healthcare provider for severe symptoms.",
        "Use prescribed medications consistently, avoid overexertion, and practice good hand hygiene. Seek advice from a healthcare provider for ongoing management.",
        "Stay active with light exercises, avoid overexertion, and maintain a healthy diet. Professional guidance from a general practitioner is beneficial.",
        "Monitor for signs of worsening symptoms, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Use prescribed medications consistently, avoid exposure to cold air, and practice good hand hygiene. Consult a nutritionist for dietary adjustments.",
        "Monitor for signs of secondary infection, avoid close contact with infected individuals, and use prescribed medications consistently. Regular follow-ups with a healthcare provider are crucial.",
        "Stay hydrated, avoid exposure to cold air, and practice good hand hygiene. Seek medical advice from a healthcare provider for ongoing management.",
        "Use prescribed medications consistently, avoid smoking, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of worsening symptoms, avoid exposure to cold air, and stay hydrated. Regular check-ups with a healthcare provider are crucial.",
        "Take prescribed medications consistently, avoid exposure to pollutants, and stay informed about drug reaction management. Seek advice from a general practitioner for ongoing care.",
        "Use prescribed medications consistently, avoid exposure to cold air, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of secondary infection, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Stay active with light exercises, avoid overexertion, and practice good hand hygiene. Seek medical advice from a healthcare provider for ongoing management."
    ],
    "Gastroesophageal Reflux Disease": [
        "Make dietary changes, avoid large meals, and consider medications. Consult a doctor for a tailored management plan.",
        "Avoid spicy and fatty foods, practice good hand hygiene, and stay hydrated. Consult a healthcare provider for severe symptoms.",
        "Use prescribed medications consistently, avoid overexertion, and practice good hand hygiene. Seek advice from a gastroenterologist for ongoing management.",
        "Stay active with light exercises, avoid overexertion, and maintain a healthy diet. Professional guidance from a general practitioner is beneficial.",
        "Monitor for signs of worsening symptoms, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Use prescribed medications consistently, avoid exposure to cold air, and practice good hand hygiene. Consult a nutritionist for dietary adjustments.",
        "Monitor for signs of secondary infection, avoid close contact with infected individuals, and use prescribed medications consistently. Regular follow-ups with a healthcare provider are crucial.",
        "Stay hydrated, avoid exposure to cold air, and practice good hand hygiene. Seek medical advice from a gastroenterologist for ongoing management.",
        "Use prescribed medications consistently, avoid smoking, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of worsening symptoms, avoid exposure to cold air, and stay hydrated. Regular check-ups with a healthcare provider are crucial.",
        "Take prescribed medications consistently, avoid exposure to pollutants, and stay informed about GERD management. Seek advice from a general practitioner for ongoing care.",
        "Use prescribed medications consistently, avoid exposure to cold air, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of secondary infection, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Stay active with light exercises, avoid overexertion, and practice good hand hygiene. Seek medical advice from a gastroenterologist for ongoing management."
    ],
    "Peptic Ulcer Disease": [
        "Avoid spicy and acidic foods, take prescribed medications, and manage stress. Regular consultation with a gastroenterologist is advised.",
        "Avoid caffeine and alcohol, practice good hand hygiene, and stay hydrated. Consult a healthcare provider for severe symptoms.",
        "Use prescribed medications consistently, avoid overexertion, and practice good hand hygiene. Seek advice from a gastroenterologist for ongoing management.",
        "Stay active with light exercises, avoid overexertion, and maintain a healthy diet. Professional guidance from a general practitioner is beneficial.",
        "Monitor for signs of worsening symptoms, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Use prescribed medications consistently, avoid exposure to cold air, and practice good hand hygiene. Consult a nutritionist for dietary adjustments.",
        "Monitor for signs of secondary infection, avoid close contact with infected individuals, and use prescribed medications consistently. Regular follow-ups with a healthcare provider are crucial.",
        "Stay hydrated, avoid exposure to cold air, and practice good hand hygiene. Seek medical advice from a gastroenterologist for ongoing management.",
        "Use prescribed medications consistently, avoid smoking, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of worsening symptoms, avoid exposure to cold air, and stay hydrated. Regular check-ups with a healthcare provider are crucial.",
        "Take prescribed medications consistently, avoid exposure to pollutants, and stay informed about peptic ulcer disease management. Seek advice from a general practitioner for ongoing care.",
        "Use prescribed medications consistently, avoid exposure to cold air, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of secondary infection, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Stay active with light exercises, avoid overexertion, and practice good hand hygiene. Seek medical advice from a gastroenterologist for ongoing management."
    ],
    "Urinary Tract Infection": [
        "Stay well-hydrated, follow prescribed antibiotics, and practice good hygiene. Consult a doctor for appropriate treatment.",
        "Avoid caffeine and alcohol, practice good hand hygiene, and stay hydrated. Consult a healthcare provider for severe symptoms.",
        "Use prescribed medications consistently, avoid overexertion, and practice good hand hygiene. Seek advice from a urologist for ongoing management.",
        "Stay active with light exercises, avoid overexertion, and maintain a healthy diet. Professional guidance from a general practitioner is beneficial.",
        "Monitor for signs of worsening symptoms, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Use prescribed medications consistently, avoid exposure to cold air, and practice good hand hygiene. Consult a nutritionist for dietary adjustments.",
        "Monitor for signs of secondary infection, avoid close contact with infected individuals, and use prescribed medications consistently. Regular follow-ups with a healthcare provider are crucial.",
        "Stay hydrated, avoid exposure to cold air, and practice good hand hygiene. Seek medical advice from a urologist for ongoing management.",
        "Use prescribed medications consistently, avoid smoking, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of worsening symptoms, avoid exposure to cold air, and stay hydrated. Regular check-ups with a healthcare provider are crucial.",
        "Take prescribed medications consistently, avoid exposure to pollutants, and stay informed about UTI management. Seek advice from a general practitioner for ongoing care.",
        "Use prescribed medications consistently, avoid exposure to cold air, and maintain a healthy weight. Consult a pharmacist for over-the-counter relief options.",
        "Monitor for signs of secondary infection, avoid crowded places, and stay hydrated. Regular consultations with a healthcare provider are important.",
        "Stay active with light exercises, avoid overexertion, and practice good hand hygiene. Seek medical advice from a urologist for ongoing management."
    ],
    "Impetigo": [
        "Clean the affected area regularly, use prescribed antibiotics, and avoid close contact with others. Medical consultation is important for proper treatment.",
        "Keep the infected area covered, avoid scratching, and practice good hygiene. Consult a dermatologist for severe cases.",
        "Use antiseptic solutions, avoid sharing personal items, and maintain a clean living environment. Regular check-ups with a healthcare provider are crucial.",
        "Apply topical antibiotics as directed, avoid touching the sores, and wash your hands frequently. Seek advice from a pediatrician for children with impetigo.",
        "Take oral antibiotics if prescribed, avoid crowded places, and practice good skin care. Professional guidance from a general practitioner is beneficial.",
        "Monitor for signs of spreading, avoid using makeup or creams on the affected area, and practice good wound care. Regular consultations with a family doctor can help manage symptoms.",
        "Use separate towels for the infected area, avoid close contact with infected individuals, and keep fingernails short. Consult a pharmacist for over-the-counter antiseptics.",
        "Monitor for signs of secondary infection, avoid sharing clothing or bedding, and use prescribed medications consistently. Regular follow-ups with a healthcare provider are important.",
        "Stay hydrated, avoid hot and humid environments, and practice good hand hygiene. Seek medical advice from a dermatologist for persistent infections.",
        "Use antibacterial soaps, avoid scratching with gloves if necessary, and maintain a healthy diet. Consult a nurse practitioner for ongoing symptoms.",
        "Keep the affected area clean and dry, avoid exposure to irritants, and practice good overall hygiene. Regular check-ups with a healthcare provider are crucial.",
        "Stay informed about impetigo prevention strategies, avoid touching your face, and use antiseptic creams as needed. Seek advice from a general practitioner for ongoing care.",
        "Take immune-boosting supplements, avoid close contact with infected individuals, and practice good skin hygiene. Consult a pediatrician for proper management in children.",
        "Stay cool with fans or air conditioning, avoid prolonged sun exposure, and ensure proper rest. Regular consultations with a family doctor are beneficial.",
        "Keep your living area clean, avoid using strong detergents, and practice good handwashing techniques. Seek medical advice from a dermatologist for severe cases."
    ]
}
