greetings = [
    "Hey there!", "Howdy partner!", "Greetings!", "Hiya!", "Yo!", "Hey, what's cooking?",
    "Top of the morning!", "Salutations!", "Hi there, friend!", "What's the word?",
    "How do you do?", "Hey, buddy!", "Hello, mate!", "Hi, how's life?", "What's shaking?",
    "Hey, how's it hanging?", "Hi, amigo!", "What's new?", "Hey, how's everything?",
    "Hello, good to see you!", "Hi there, what's the scoop?", "Hey, how's life treating you?",
    "Hi, what's happening?", "Hey, what's the haps?", "Hi, what's going on?",
    "Hello, how's your day?", "Hi, how's your week?", "What's the latest?",
    "Hey, how's your morning?", "Hi, how's your afternoon?", "Hello, how's your evening?",
    "What's up, champ?", "Hey, how's it going, pal?", "Hi there, what's new?",
    "Hey, how's everything going?", "Hi there, how's it been?", "Hello, what's happening?",
    "Hey, how's it going, buddy?", "What's good, friend?", "Hi there, how's life?",
    "Hello, how are things?", "Hey, what's the good word?", "Hi, how's it going, champ?",
    "Hey, how's your day?", "Hi, what's the word?", "Hey, how's it hanging, mate?",
    "Hello, how's life treating you?", "Hi, what's new with you?", "Hey, how's it going, amigo?",
    "Hello, how's everything going?", "Hi, what's the scoop?", "Hey, what's new, partner?"
    "hello!", "hii", "hello", "hii!", "hi", "hi there!", "heyy", "good morning", "good morning!",
    "good afternoon", "good evening", "hey", "how are you", "how are you?", "how is it going",
    "how is it going?", "what's up?", "hey, how are you?", "what is popping", "good to see you!", "howdy!",
    "hi, nice to meet you.", "hiya!", "hi, what's new?", "hey, how's your day?", "hi, how have you been?",
    "greetings", "good day", "hello there", "hey there", "yo", "sup", "what's good", "how's it going?",
    "how's everything?", "how's life?", "what's happening?", "how are things?", "pleased to meet you",
    "hi everyone", "how's your morning?", "how's your afternoon?", "how's your evening?",
    "nice to see you", "nice to meet you", "good to hear from you", "long time no see",
    "hey, long time no see", "hey, what's up?", "how have you been?", "what's new?",
    "hey, what's new with you?", "hi there, how's it going?", "hey, what's new?", "hi there, what's up?",
    "hey there, how have you been?", "hi there, how are things?", "what's going on?",
    "how's everything going?", "how's it been?", "hey!", "hey", "hi there", "hi there!", "greetings", "greetings!",
    "ola", "oi","ola!","oi!"
]

responses = [
    "Greetings! I'm a medical chatbot here to assist you. Share your symptoms explicitly, and I'll offer possible disease predictions. I can also help book an appointment if necessary.",
    "Hi there! Share your symptoms with me, and I'll offer possible disease predictions. If required, I can also help you schedule an appointment with a healthcare professional.",
    "Hello! How can I assist you today? Please provide detailed symptoms, and I'll help identify potential conditions. If needed, I can also assist in scheduling an appointment.",
    "Greetings! I'm a medical chatbot ready to assist you. Share your symptoms explicitly, and I'll offer possible disease predictions. I can also help book an appointment if needed.",
    "Hi there! I'm here to help with your health questions. Describe your symptoms in detail, and I'll predict possible diseases. If necessary, I can help you schedule an appointment.",
    "Hello! Describe your symptoms, and I'll help identify potential diseases. If you need to see a healthcare professional, I can assist in scheduling an appointment.",
    "Welcome! I'm here to assist you with your health concerns. Please describe your symptoms in detail, and I'll help identify potential diseases. If you need to see a doctor, I can help you book an appointment too.",
    "Greetings! I'm here to help with medical predictions. Describe your symptoms explicitly, and I'll offer insights into potential diseases. I can also assist in booking an appointment.",
    "Hi, I'm the medical chatbot. I've been trained to predict diseases from symptoms. The more explicit you are about your symptoms, the better I can assist you. Additionally, I can help you book an appointment.",
    "Hi! I'm here to help with your health concerns. Please describe your symptoms in detail, and I'll suggest possible diseases. I can also help book an appointment if necessary.",
    "Hi there! I'm here to help with your health questions. Describe your symptoms explicitly, and I'll predict possible diseases. If required, I can also help you schedule an appointment.",
    "How can I assist you today? I'm a medical chatbot trained to predict diseases based on symptoms. Please be explicit while describing your symptoms. If needed, I can help you book an appointment.",
    "Hello! I'm a medical chatbot with expertise in predicting diseases from symptoms. Please describe your symptoms explicitly to receive accurate insights. I can also assist in booking an appointment if needed.",
    "Hello! I'm here to assist with your symptoms. Describe them in detail, and I'll predict potential diseases. If you need an appointment, I can help with that too.",
    "Hi there! Share your symptoms with me, and I'll provide possible disease predictions. If needed, I can also assist in scheduling an appointment with a healthcare professional.",
    "Welcome to the medical chatbot. To assist you accurately, please share your symptoms in explicit detail. If necessary, I can help you book an appointment with a doctor.",
    "Hi! I'm here to assist with your health concerns. Please describe your symptoms in detail, and I'll suggest possible conditions. I can also help book an appointment if needed.",
    "Hi! I'm a medical chatbot here to help you. Describe your symptoms explicitly, and I'll provide possible disease predictions. I can also help book an appointment if required.",
    "Hello! How can I assist you today? Please provide detailed symptoms, and I'll help identify potential diseases. If required, I can also assist in scheduling an appointment.",
    "Hi! I'm here to help with your medical concerns. Share your symptoms in detail, and I'll predict possible diseases. I can also help schedule an appointment if you need one.",
    "Hello! Describe your symptoms, and I'll help identify potential diseases. If you need to see a healthcare professional, I can assist in scheduling an appointment.",
    "Greetings! Please tell me about your symptoms, and I'll offer potential disease predictions. If needed, I can assist in booking an appointment with a doctor.",
    "Hi, I specialize in medical predictions based on symptoms. Kindly provide detailed symptoms for accurate disease predictions. If necessary, I can also help you schedule an appointment.",
    "Hi there! I'm here to help with your health questions. Describe your symptoms in detail, and I'll predict possible conditions. If needed, I can help you schedule an appointment.",
    "Greetings! I'm a medical chatbot here to assist you. Share your symptoms in detail, and I'll offer possible disease predictions. I can also help book an appointment if needed.",
    "Welcome! I'm a medical chatbot ready to help. Share your symptoms, and I'll provide possible disease predictions. If required, I can assist in scheduling an appointment.",
    "Hello! I'm here to help you with your symptoms. Describe them in detail, and I'll predict potential diseases. If you need an appointment, I can assist with that too.",
    "Greetings! Please tell me about your symptoms, and I'll suggest potential conditions. If necessary, I can assist in booking an appointment with a doctor.",
    "Hi there! Share your symptoms with me, and I'll suggest possible diseases. If necessary, I can also help you schedule an appointment with a healthcare professional.",
    "Hello! I'm a medical chatbot capable of predicting diseases based on the symptoms you provide. Your explicit symptom description will help me assist you better, and I can also help schedule an appointment if required.",
    "Welcome! I'm a medical chatbot. Describe your symptoms, and I'll suggest possible conditions. If you need to see a healthcare professional, I can assist with that too.",
    "Hi! I'm here to assist with your health concerns. Please describe your symptoms in detail, and I'll suggest possible conditions. I can also help book an appointment if needed.",
    "Hello! Describe your symptoms, and I'll help identify potential diseases. If you need to see a healthcare professional, I can assist in scheduling an appointment.",
    "Hi! I'm a medical chatbot ready to help. Share your symptoms, and I'll provide possible disease predictions. If required, I can assist in scheduling an appointment.",
    "Hi! I'm a medical chatbot here to help. Describe your symptoms explicitly, and I'll provide possible disease predictions. I can also help book an appointment if needed.",
    "Hello! How can I assist you today? Please provide detailed symptoms, and I'll help identify potential conditions. If needed, I can also assist in scheduling an appointment.",
    "Hi there! I'm here to help with your health questions. Describe your symptoms in detail, and I'll predict possible diseases. If necessary, I can help you schedule an appointment.",
    "Thank you for using our medical chatbot. Please provide the symptoms you're experiencing, and I'll do my best to predict the possible disease. If needed, I can also assist in booking an appointment with a healthcare professional.",
    "Hey! I'm your medical chatbot. Describe your symptoms with as much detail as you can, and I'll generate potential disease predictions. Additionally, I can assist in booking an appointment.",
    "Greetings! Please tell me about your symptoms, and I'll offer predictions for potential diseases. If necessary, I can assist in booking an appointment with a doctor.",
    "Welcome! I'm here to assist you with your health concerns. Please describe your symptoms in detail, and I'll help identify potential diseases. If you need to see a doctor, I can help you book an appointment too."
]

farewell = ["Adeus","adeus","see you soon!", "see you!", "be well!", "take it easy!", "goodbye for now!","catch you,later"
            "goodbye", "have a good one!", "farewell, my friend!", "thanks", "all the best!", "good-bye",
            "catch you later!", "take care!", "bye", "have a great day!", "peace out!","peace out","see you next time!","see you next time"
            "until next time!", "catch you later!", "later", "see you", "be safe!", "thank you", "good day!",
            "hasta la vista!", "byebye!", "until we meet again!", "stay well!", "toodles!","see ya",
            "bye for now!", "adios!", "bye bye", "I’m out!", "until we chat again!", "later days!",
            "take care of yourself!","ciao!", "thank", "have a nice day!", "stay safe and goodbye!", "good luck!", "so long!", "see-you",
            "keep in touch!", "later!","off I go!", "byebye", "good bye", "see you around!", "farewell!", "best wishes!",
            "see ya later!", "bon voyage!", "stay cool!", "have fun!", "keep smiling!", "later gator!",
            "I'm off!", "Godspeed!", "stay awesome!", "be seeing you!", "take it easy, pal!", "safe travels!",
            "have a blast!", "cheerio!", "don’t be a stranger!", "stay strong!", "see you when I see you!",
            "happy trails!", "stay golden!", "until then!", "see you on the flip side!", "be good!",
            "until we meet!", "have a good one!", "be happy!", "rock on!", "later tater!", "goodbye, friend!",
            "catch you on the rebound!", "until next we meet!"
            ]

replies = [
    "Take care and stay vigilant about your health. Bye!",
    "Thank you for chatting with us. Wishing you good health! Bye!",
    "Your health is important to us. Farewell!", "Stay informed and stay healthy. Goodbye!",
    "It was a pleasure assisting you. Goodbye!", "Take care of yourself and stay positive. Bye!",
    "Health and happiness to you. Farewell!", "Take good care of yourself. Goodbye!",
    "Wishing you wellness and happiness. Goodbye!", "May your health improve soon. Farewell!",
    "Stay safe and take care of your health. Bye!", "Thank you for choosing us. Stay well! Goodbye!",
    "Goodbye! Don’t forget to follow up on your health.", "Best of luck with your health. Goodbye!",
    "Stay healthy and positive! Bye!", "Remember to take your medications on time. Goodbye!",
    "Stay strong and healthy. Goodbye!", "We're here for you anytime. Take care! Bye!",
    "It was nice talking to you. Stay healthy and take care. Bye!", "Prioritize your well-being. Farewell!",
    "Wishing you good health and happiness. Bye!", "Best wishes for your health journey. Farewell!",
    "Follow up with your healthcare provider. Goodbye!", "Thank you for your trust. Stay well! Bye!",
    "Your health matters. Take care! Goodbye!", "Stay well and have a great day! Farewell!",
    "Take care and don’t hesitate to reach out again. Goodbye!", "Take care and remain positive. Bye!",
    "Stay proactive about your health. Goodbye!", "Thank you for chatting with us. Stay well! Farewell!",
    "Take care and best of luck with your health. Bye!", "Thank you for reaching out. Stay safe and well! Bye!",
    "We wish you a speedy recovery. Goodbye!", "Stay determined and healthy. Goodbye!",
    "Keep up the good work on your health. Bye!", "Stay well-informed and healthy. Goodbye!",
    "Don’t forget to keep in touch with your doctor. Goodbye!", "Take care and stay positive. Farewell!",
    "We're here for you anytime. Take care! Bye!", "Thank you for using our service. Stay well! Farewell!",
    "Take good care of your body and mind. Bye!", "We care about your health. Farewell!",
    "Stay hopeful and healthy. Farewell!", "We hope to hear from you again. Goodbye!",
    "Your health journey is important. Farewell!", "Take care and stay healthy! Goodbye!",
    "We wish you the best in health. Farewell!", "It was a pleasure assisting you. Goodbye!",
    "Keep following your health plan. Farewell!", "Stay committed to your health goals. Bye!",
    "Take care and stay healthy! Goodbye!"
]
